make README.MD, fix pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,11 +1,10 @@
 #!/bin/sh
-testRun = "python3 tests.py
-exec $testRun
+python3 tests.py
 
-exitCode=$?
-if [ x"$exitCode" == x"0" ]
-then
+if [ $? = 0 ];then
+  echo 'Tests passed'
   exit 0
 else
+  echo 'Tests failed'
   exit 1
 fi
